=== inab/rd-connect-user-management/libs/RDConnect/userValidation.json
{
	"id": "http://rd-connect.eu/cas/json-schemas/userValidation#CASUser",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "RD-Connect CAS user",
	"type": "object",
	"properties": {
		"givenName": {
			"title": "First / given name",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"surname": {
			"title": "Surname(s)",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"userPassword": {
			"title": "Password",
			"type": "string",
			"minLength": 1
		},
		"username": {
			"title": "The username",
			"type": "string",
			"minLength": 1
		},
		"organizationalUnit": {
			"title": "The organizational unit where this user entry is living",
			"type": "string",
			"minLength": 1
		},
		"enabled": {
			"title": "User enabled",
			"type": "boolean"
		},
		"cn": {
			"title": "Common name (usually givenName + surname)",
			"type": "string",
			"minLength": 1
		},
		"email": {
			"title": "The e-mail address(es) of the user",
			"type": "array",
			"format": "email",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"minLength": 1,
				"format": "email"
			}
		},
		"userCategory": {
			"title": "User category",
			"type": "string",
			"enum": [ "PI", "Researcher", "PhD", "Student", "Technician", "Collaborator", "External"]
		},
		"title": {
			"title": "Preferred way to address the user: Mr., Ms., Miss, Dr., MD., Dame, Lord, etc...",
			"type": "string"
		},
		"picture": {
			"title": "A JPEG picture of the user",
			"type": "string",
			"format": "data-url",
			"media": {
				"type": "image/jpeg",
				"binaryEncoding": "base64"
			}
		},
		"telephoneNumber": {
			"title": "A contact phone number, including the international prefix",
			"type": "array",
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"facsimileTelephoneNumber": {
			"title": "A fax number, including the international prefix",
			"type": "array",
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"registeredAddress": {
			"title": "The address to physically reach the user",
			"type": "string"
		},
		"postalAddress": {
			"title": "The address to send traditional mail to the user, when it is different from the physical address of the user",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the user",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the user",
						"type": "string",
						"minLength": 1,
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["ORCID","Publication","LinkedIn","ResearchGate","DepartmentProfile"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		},
		"groups": {
			"title": "The list of groups where this user is registered in",
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"minLength": 1
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"givenName",
		"surname",
		"username",
		"email"
	],
	"dependencies": {
		"postalAddress": ["registeredAddress"]
	}
}

=== inab/rd-connect-user-management/api-tests/userTest.json
{
    "organizationalUnit": "default",
    "cn": "Perico Palotes",
    "surname": [
        "Palotes",
        "Grandes"
    ],
    "username": "p.palotes",
    "email": [
        "pericopalotes23@nowhere.org"
    ],
    "userPassword": "mi.casa",
    "givenName": [
        "Perico"
    ],
    "enabled": true
}
